import '../../models/transaction_model.dart';
import '../../models/user_model.dart';

class MockDataService {
  MockDataService._();

  static UserModel get currentUser => const UserModel(
        id: 'u001',
        name: 'Abhishek Patidar',
        email: 'abhishek@example.com',
        monthlyBudget: 80000,
      );

  static double get currentMonthSpend => 62480.50;
  static double get lastMonthSpend => 54200.00;
  static double get percentChange =>
      ((currentMonthSpend - lastMonthSpend) / lastMonthSpend) * 100;

  static List<TransactionModel> get allTransactions => [
        // Food (12 transactions)
        TransactionModel(
          id: 't001',
          title: 'Swiggy Order',
          subtitle: 'Burger King, Indore',
          amount: 485,
          type: TransactionType.expense,
          category: CategoryType.food,
          date: DateTime.now().subtract(const Duration(hours: 2)),
        ),
        TransactionModel(
          id: 't002',
          title: 'Zomato Delivery',
          subtitle: 'Pizza Hut',
          amount: 720,
          type: TransactionType.expense,
          category: CategoryType.food,
          date: DateTime.now().subtract(const Duration(days: 1)),
        ),
        TransactionModel(
          id: 't003',
          title: 'Big Basket',
          subtitle: 'Grocery Shopping',
          amount: 2340,
          type: TransactionType.expense,
          category: CategoryType.food,
          date: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
        ),
        TransactionModel(
          id: 't004',
          title: 'Chai & Snacks',
          subtitle: 'Local Canteen',
          amount: 85,
          type: TransactionType.expense,
          category: CategoryType.food,
          date: DateTime.now().subtract(const Duration(days: 2)),
        ),
        TransactionModel(
          id: 't005',
          title: 'McDonald\'s',
          subtitle: 'Palasia, Indore',
          amount: 540,
          type: TransactionType.expense,
          category: CategoryType.food,
          date: DateTime.now().subtract(const Duration(days: 2, hours: 5)),
        ),
        TransactionModel(
          id: 't006',
          title: 'Domino\'s Pizza',
          subtitle: 'Vijay Nagar',
          amount: 680,
          type: TransactionType.expense,
          category: CategoryType.food,
          date: DateTime.now().subtract(const Duration(days: 3)),
        ),
        TransactionModel(
          id: 't007',
          title: 'Milk & Bread',
          subtitle: 'D-Mart',
          amount: 230,
          type: TransactionType.expense,
          category: CategoryType.food,
          date: DateTime.now().subtract(const Duration(days: 4)),
        ),
        TransactionModel(
          id: 't008',
          title: 'Restaurant Dinner',
          subtitle: 'The Grill House',
          amount: 1850,
          type: TransactionType.expense,
          category: CategoryType.food,
          date: DateTime.now().subtract(const Duration(days: 5)),
        ),
        TransactionModel(
          id: 't009',
          title: 'Juice & Fruits',
          subtitle: 'Morning Fresh',
          amount: 180,
          type: TransactionType.expense,
          category: CategoryType.food,
          date: DateTime.now().subtract(const Duration(days: 6)),
        ),
        TransactionModel(
          id: 't010',
          title: 'Swiggy Instamart',
          subtitle: 'Quick Grocery',
          amount: 450,
          type: TransactionType.expense,
          category: CategoryType.food,
          date: DateTime.now().subtract(const Duration(days: 7)),
        ),
        TransactionModel(
          id: 't011',
          title: 'Café Coffee Day',
          subtitle: 'C21 Mall',
          amount: 320,
          type: TransactionType.expense,
          category: CategoryType.food,
          date: DateTime.now().subtract(const Duration(days: 8)),
        ),
        TransactionModel(
          id: 't012',
          title: 'Monthly Groceries',
          subtitle: 'Big Bazaar',
          amount: 3200,
          type: TransactionType.expense,
          category: CategoryType.food,
          date: DateTime.now().subtract(const Duration(days: 9)),
        ),

        // Travel (8 transactions)
        TransactionModel(
          id: 't013',
          title: 'Ola Cab',
          subtitle: 'Airport Drop',
          amount: 780,
          type: TransactionType.expense,
          category: CategoryType.travel,
          date: DateTime.now().subtract(const Duration(days: 1, hours: 6)),
        ),
        TransactionModel(
          id: 't014',
          title: 'IRCTC Ticket',
          subtitle: 'Indore → Mumbai',
          amount: 1250,
          type: TransactionType.expense,
          category: CategoryType.travel,
          date: DateTime.now().subtract(const Duration(days: 3)),
        ),
        TransactionModel(
          id: 't015',
          title: 'Uber Ride',
          subtitle: 'Daily Commute',
          amount: 240,
          type: TransactionType.expense,
          category: CategoryType.travel,
          date: DateTime.now().subtract(const Duration(days: 4)),
        ),
        TransactionModel(
          id: 't016',
          title: 'Rapido Bike',
          subtitle: 'Office to Home',
          amount: 65,
          type: TransactionType.expense,
          category: CategoryType.travel,
          date: DateTime.now().subtract(const Duration(days: 5)),
        ),
        TransactionModel(
          id: 't017',
          title: 'Flight Booking',
          subtitle: 'IndiGo - BOM to DEL',
          amount: 4800,
          type: TransactionType.expense,
          category: CategoryType.travel,
          date: DateTime.now().subtract(const Duration(days: 7)),
        ),
        TransactionModel(
          id: 't018',
          title: 'Petrol Fill',
          subtitle: 'HP Petrol Pump',
          amount: 1500,
          type: TransactionType.expense,
          category: CategoryType.travel,
          date: DateTime.now().subtract(const Duration(days: 10)),
        ),
        TransactionModel(
          id: 't019',
          title: 'Metro Card Recharge',
          subtitle: 'Delhi Metro',
          amount: 500,
          type: TransactionType.expense,
          category: CategoryType.travel,
          date: DateTime.now().subtract(const Duration(days: 12)),
        ),
        TransactionModel(
          id: 't020',
          title: 'Taxi Rental',
          subtitle: 'City Tour - Udaipur',
          amount: 2200,
          type: TransactionType.expense,
          category: CategoryType.travel,
          date: DateTime.now().subtract(const Duration(days: 14)),
        ),

        // Shopping (10 transactions)
        TransactionModel(
          id: 't021',
          title: 'Amazon Purchase',
          subtitle: 'Laptop Stand + Keyboard',
          amount: 3499,
          type: TransactionType.expense,
          category: CategoryType.shopping,
          date: DateTime.now().subtract(const Duration(days: 1)),
        ),
        TransactionModel(
          id: 't022',
          title: 'Flipkart Order',
          subtitle: 'Headphones - boAt',
          amount: 1999,
          type: TransactionType.expense,
          category: CategoryType.shopping,
          date: DateTime.now().subtract(const Duration(days: 3)),
        ),
        TransactionModel(
          id: 't023',
          title: 'Myntra Fashion',
          subtitle: 'Casual Shirts x3',
          amount: 2499,
          type: TransactionType.expense,
          category: CategoryType.shopping,
          date: DateTime.now().subtract(const Duration(days: 5)),
        ),
        TransactionModel(
          id: 't024',
          title: 'Ajio Sale',
          subtitle: 'Nike Shoes',
          amount: 4599,
          type: TransactionType.expense,
          category: CategoryType.shopping,
          date: DateTime.now().subtract(const Duration(days: 6)),
        ),
        TransactionModel(
          id: 't025',
          title: 'Croma Electronics',
          subtitle: 'USB Hub',
          amount: 999,
          type: TransactionType.expense,
          category: CategoryType.shopping,
          date: DateTime.now().subtract(const Duration(days: 8)),
        ),
        TransactionModel(
          id: 't026',
          title: 'H&M',
          subtitle: 'Palladium Mall',
          amount: 3200,
          type: TransactionType.expense,
          category: CategoryType.shopping,
          date: DateTime.now().subtract(const Duration(days: 9)),
        ),
        TransactionModel(
          id: 't027',
          title: 'Meesho Order',
          subtitle: 'Home Decor Items',
          amount: 650,
          type: TransactionType.expense,
          category: CategoryType.shopping,
          date: DateTime.now().subtract(const Duration(days: 11)),
        ),
        TransactionModel(
          id: 't028',
          title: 'Nykaa Beauty',
          subtitle: 'Skincare Products',
          amount: 1350,
          type: TransactionType.expense,
          category: CategoryType.shopping,
          date: DateTime.now().subtract(const Duration(days: 13)),
        ),
        TransactionModel(
          id: 't029',
          title: 'Apple Store',
          subtitle: 'iPhone Case & Cable',
          amount: 2499,
          type: TransactionType.expense,
          category: CategoryType.shopping,
          date: DateTime.now().subtract(const Duration(days: 15)),
        ),
        TransactionModel(
          id: 't030',
          title: 'Books & Stationery',
          subtitle: 'Crossword Bookstore',
          amount: 890,
          type: TransactionType.expense,
          category: CategoryType.shopping,
          date: DateTime.now().subtract(const Duration(days: 17)),
        ),

        // Health (7 transactions)
        TransactionModel(
          id: 't031',
          title: 'Gym Membership',
          subtitle: 'Anytime Fitness',
          amount: 2500,
          type: TransactionType.expense,
          category: CategoryType.health,
          date: DateTime.now().subtract(const Duration(days: 1)),
        ),
        TransactionModel(
          id: 't032',
          title: 'Apollo Pharmacy',
          subtitle: 'Monthly Medicines',
          amount: 890,
          type: TransactionType.expense,
          category: CategoryType.health,
          date: DateTime.now().subtract(const Duration(days: 4)),
        ),
        TransactionModel(
          id: 't033',
          title: 'Doctor Consultation',
          subtitle: 'Dr. Sharma - Clinic',
          amount: 500,
          type: TransactionType.expense,
          category: CategoryType.health,
          date: DateTime.now().subtract(const Duration(days: 7)),
        ),
        TransactionModel(
          id: 't034',
          title: 'Blood Test',
          subtitle: 'SRL Diagnostics',
          amount: 1200,
          type: TransactionType.expense,
          category: CategoryType.health,
          date: DateTime.now().subtract(const Duration(days: 10)),
        ),
        TransactionModel(
          id: 't035',
          title: 'Protein Powder',
          subtitle: 'HealthKart',
          amount: 2800,
          type: TransactionType.expense,
          category: CategoryType.health,
          date: DateTime.now().subtract(const Duration(days: 12)),
        ),
        TransactionModel(
          id: 't036',
          title: 'Yoga Class',
          subtitle: 'The Yoga Studio',
          amount: 1500,
          type: TransactionType.expense,
          category: CategoryType.health,
          date: DateTime.now().subtract(const Duration(days: 14)),
        ),
        TransactionModel(
          id: 't037',
          title: 'Eye Checkup',
          subtitle: 'Vision Care Center',
          amount: 300,
          type: TransactionType.expense,
          category: CategoryType.health,
          date: DateTime.now().subtract(const Duration(days: 18)),
        ),

        // Entertainment (6 transactions)
        TransactionModel(
          id: 't038',
          title: 'Netflix Premium',
          subtitle: 'Monthly Subscription',
          amount: 649,
          type: TransactionType.expense,
          category: CategoryType.entertainment,
          date: DateTime.now().subtract(const Duration(days: 2)),
        ),
        TransactionModel(
          id: 't039',
          title: 'PVR Cinema',
          subtitle: 'Movie - Kalki 2898',
          amount: 840,
          type: TransactionType.expense,
          category: CategoryType.entertainment,
          date: DateTime.now().subtract(const Duration(days: 5)),
        ),
        TransactionModel(
          id: 't040',
          title: 'Spotify Premium',
          subtitle: 'Music Subscription',
          amount: 119,
          type: TransactionType.expense,
          category: CategoryType.entertainment,
          date: DateTime.now().subtract(const Duration(days: 6)),
        ),
        TransactionModel(
          id: 't041',
          title: 'Amazon Prime',
          subtitle: 'Annual Subscription',
          amount: 1499,
          type: TransactionType.expense,
          category: CategoryType.entertainment,
          date: DateTime.now().subtract(const Duration(days: 10)),
        ),
        TransactionModel(
          id: 't042',
          title: 'Gaming - Steam',
          subtitle: 'GTA VI Pre-order',
          amount: 3499,
          type: TransactionType.expense,
          category: CategoryType.entertainment,
          date: DateTime.now().subtract(const Duration(days: 13)),
        ),
        TransactionModel(
          id: 't043',
          title: 'YouTube Premium',
          subtitle: 'Monthly Plan',
          amount: 189,
          type: TransactionType.expense,
          category: CategoryType.entertainment,
          date: DateTime.now().subtract(const Duration(days: 16)),
        ),

        // Bills (8 transactions)
        TransactionModel(
          id: 't044',
          title: 'Electricity Bill',
          subtitle: 'MPCZ - June 2025',
          amount: 1850,
          type: TransactionType.expense,
          category: CategoryType.bills,
          date: DateTime.now().subtract(const Duration(days: 3)),
        ),
        TransactionModel(
          id: 't045',
          title: 'Airtel Broadband',
          subtitle: 'Internet - 300 Mbps',
          amount: 999,
          type: TransactionType.expense,
          category: CategoryType.bills,
          date: DateTime.now().subtract(const Duration(days: 5)),
        ),
        TransactionModel(
          id: 't046',
          title: 'Jio Prepaid',
          subtitle: 'Mobile Recharge',
          amount: 599,
          type: TransactionType.expense,
          category: CategoryType.bills,
          date: DateTime.now().subtract(const Duration(days: 8)),
        ),
        TransactionModel(
          id: 't047',
          title: 'House Rent',
          subtitle: 'Vijay Nagar, Indore',
          amount: 18000,
          type: TransactionType.expense,
          category: CategoryType.bills,
          date: DateTime.now().subtract(const Duration(days: 10)),
        ),
        TransactionModel(
          id: 't048',
          title: 'Gas Bill',
          subtitle: 'Indore Gas Agency',
          amount: 850,
          type: TransactionType.expense,
          category: CategoryType.bills,
          date: DateTime.now().subtract(const Duration(days: 12)),
        ),
        TransactionModel(
          id: 't049',
          title: 'Water Bill',
          subtitle: 'IMC Water Supply',
          amount: 280,
          type: TransactionType.expense,
          category: CategoryType.bills,
          date: DateTime.now().subtract(const Duration(days: 15)),
        ),
        TransactionModel(
          id: 't050',
          title: 'DTH Recharge',
          subtitle: 'Tata Play - HD Pack',
          amount: 399,
          type: TransactionType.expense,
          category: CategoryType.bills,
          date: DateTime.now().subtract(const Duration(days: 18)),
        ),
        TransactionModel(
          id: 't051',
          title: 'Credit Card Bill',
          subtitle: 'HDFC Credit Card',
          amount: 12500,
          type: TransactionType.expense,
          category: CategoryType.bills,
          date: DateTime.now().subtract(const Duration(days: 20)),
        ),

        // Education (4 transactions)
        TransactionModel(
          id: 't052',
          title: 'Udemy Course',
          subtitle: 'Flutter & Dart Bootcamp',
          amount: 499,
          type: TransactionType.expense,
          category: CategoryType.education,
          date: DateTime.now().subtract(const Duration(days: 4)),
        ),
        TransactionModel(
          id: 't053',
          title: 'Coursera Plus',
          subtitle: 'Monthly Subscription',
          amount: 2999,
          type: TransactionType.expense,
          category: CategoryType.education,
          date: DateTime.now().subtract(const Duration(days: 9)),
        ),
        TransactionModel(
          id: 't054',
          title: 'Technical Books',
          subtitle: 'Clean Code + DSA',
          amount: 1200,
          type: TransactionType.expense,
          category: CategoryType.education,
          date: DateTime.now().subtract(const Duration(days: 15)),
        ),
        TransactionModel(
          id: 't055',
          title: 'LinkedIn Learning',
          subtitle: 'Annual Plan',
          amount: 1999,
          type: TransactionType.expense,
          category: CategoryType.education,
          date: DateTime.now().subtract(const Duration(days: 22)),
        ),

        // Others (2 transactions)
        TransactionModel(
          id: 't056',
          title: 'ATM Withdrawal',
          subtitle: 'SBI ATM',
          amount: 5000,
          type: TransactionType.expense,
          category: CategoryType.others,
          date: DateTime.now().subtract(const Duration(days: 6)),
        ),
        TransactionModel(
          id: 't057',
          title: 'Miscellaneous',
          subtitle: 'Various Expenses',
          amount: 750,
          type: TransactionType.expense,
          category: CategoryType.others,
          date: DateTime.now().subtract(const Duration(days: 19)),
        ),
      ];
}
